environment:
  sumo_cfg: 'data/sumo_20vehicles/test.sumocfg'
  net_file: 'data/sumo_20vehicles/helsinki.net.xml'
  route_file: 'data/sumo_20vehicles/test.rou.xml'
  out_csv_name: 'data/sumo_20vehicles/out'
  path: 'data/simple_helsinki'
  use_gui: False
  virtual_display:  (3200, 1800)
  log_level: 'INFO'
  begin_time: 0
  num_seconds: 3600
  max_depart_delay: 100000
  waiting_time_memory: 1000
  time_to_teleport: -1
  single_agent: False
  reward_fn: 'diff-waiting-time'
  add_system_info: True
  add_per_agent_info: True
  fixed_ts: False
  sumo_warnings: True
  additional_sumo_cmd: ''
  render_mode: 'human'
  omnet:
    sumo_time_path: '/home/vfogsim/Documents/tmp/sumo_ts.txt'
    rllib_time_path: '/home/vfogsim/Documents/tmp/rllib_ts.txt'
    user_road: '/home/vfogsim/Documents/tmp/user_road/'
    user_route: '/home/vfogsim/Documents/tmp/user_route/'
    user_task_served: '/home/vfogsim/Documents/tmp/user_task_served'
    user_task_unserved: '/home/vfogsim/Documents/tmp/user_task_unserved'
    vfn_road: '/home/vfogsim/Documents/tmp/vfn_road/'
    vfn_route: '/home/vfogsim/Documents/tmp/vfn_route/'
    action_path: '/home/vfogsim/Documents/tmp/vfn_action'
  episode_env_steps: 300
  num_agents: 3
  agent_init:
    0:
      vfn_id: '0'
      vfn_name: 'car[0]'
      next_action_time: 0.0
      CPU_capacity: 1.0
      GPU_capacity: 1.0
      max_usr_num: 5
      road_id: '29186154#5'
    1:
      vfn_id: '1'
      vfn_name: 'car[1]'
      next_action_time: 0.0
      CPU_capacity: 1.0
      GPU_capacity: 1.0
      max_usr_num: 5
      road_id: '36729014#2'
    2:
      vfn_id: '2'
      vfn_name: 'car[2]'
      next_action_time: 0.0
      CPU_capacity: 1.0
      GPU_capacity: 1.0
      max_usr_num: 5
      road_id: '8014829#3'
train:
  num_workers: 1
  framework: 'torch'
  stop_iters: 1000
  log_level: 'WARN'
  batch_mode: 'complete_episodes'
  stop_timesteps: 3000
  stop_reward: 10000000
  num_policies: 1
  save_iters: 5
PPO_config:
  min_time_s_per_iteration: 10
  rollout_fragment_length: 10
  gamma: 0.9
  lr: 0.001
  num_workers: 1
  framework: 'torch'
  train_batch_size: 32
  sgd_minibatch_size: 32
  no_done_at_end: True
  grad_clip: 100
#  model:
#    fcnet_hiddens: [4, 4]
